name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: Print Go version
        run: go version
      
      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run vet
        run: go vet ./...

      - name: Install StaticCheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run StaticCheck
        run: staticcheck ./...

      - name: Install GoLint
        run: go install golang.org/x/lint/golint@latest

      - name: Run Golint
        run: golint ./...

      - name: Run test
        run: go test -race -coverprofile=coverage.out -vet=off ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3